//
// Created by sine on 19-1-15.
//

#ifndef SWEETPOTATO_SIP_HEADER_H
#define SWEETPOTATO_SIP_HEADER_H
typedef enum sip_header_type_e {
    sip_type_Accept,
    sip_type_Accept_Contact,
    sip_type_Accept_Encoding,
    sip_type_Accept_Language,
    sip_type_Accept_Resource_Priority,
    sip_type_Alert_Info,
    sip_type_Allow,
    sip_type_Allow_Events,
    sip_type_Answer_Mode,
    sip_type_Authentication_Info,
    sip_type_Authorization,
    sip_type_Call_ID,
    sip_type_Call_Info,
    sip_type_Cellular_Network_Info,
    sip_type_Contact,
    sip_type_Content_Disposition,
    sip_type_Content_Encoding,
    sip_type_Content_ID,
    sip_type_Content_Language,
    sip_type_Content_Length,
    sip_type_Content_Type,
    sip_type_CSeq,
    sip_type_Date,
    sip_type_Encryption,//Deprecated
    //sip_type_Dummy,
    sip_type_Error_Info,
    sip_type_Event,
    sip_type_Expires,
    sip_type_Feature_Caps,
    sip_type_Flow_Timer,
    sip_type_From,
    sip_type_Geolocation,
    sip_type_Geolocation_Error,
    sip_type_Geolocation_Routing,
    sip_type_Hide,//Deprecated
    sip_type_History_Info,
    sip_type_Identity,
    sip_type_Identity_Info,//Deprecated
    sip_type_Info_Package,
    sip_type_In_Reply_To,
    sip_type_Join,
    sip_type_Max-Breadth,//
    sip_type_Max_Forwards,
    sip_type_MIME_Version,
    sip_type_Min_Expires,
    sip_type_Min_SE,
    sip_type_Organization,
    sip_type_Path,
    sip_type_Permission_Missing,//
    sip_type_Policy_Contact,//
    sip_type_Policy_ID,//
    sip_type_Priv_Answer_Mode,//
    sip_type_Priority,
    sip_type_Privacy,
    sip_type_Proxy_Authenticate,
    sip_type_Proxy_Authorization,
    sip_type_Proxy_Require,
    sip_type_RAck,
    sip_type_Reason,
    sip_type_Record_Route,
    sip_type_Reason_Phrase,//
    sip_type_Recv_Info,//
    sip_type_Refer_Events_At,//
    sip_type_Refer_Sub,
    sip_type_Refer_To,
    sip_type_Referred_By,
    sip_type_Reject_Contact,
    sip_type_Relayed_Charge,//
    sip_type_Replaces,
    sip_type_Reply_To,
    sip_type_Request_Disposition,
    sip_type_Require,
    sip_type_Resource_Priority,
    sip_type_Resource_Share,//
    sip_type_Response_Key,//Deprecated
    sip_type_Restoraion_Info,//
    sip_type_Retry_After,
    sip_type_Route,
    sip_type_RSeq,
    sip_type_Security_Client,
    sip_type_Security_Server,
    sip_type_Security_Verify,
    sip_type_Server,
    sip_type_Service_Route,
    sip_type_Session_Expires,
    sip_type_Session_ID,//
    sip_type_SIP_ETag,
    sip_type_SIP_If_Match,
    sip_type_Subject,
    sip_type_Subscription_State,
    sip_type_Supported,
    sip_type_Suppress_If_Match,//
    sip_type_Target_Dialog,
    sip_type_Timestamp,
    sip_type_To,
    sip_type_Unsupported,
    sip_type_Trigger_Consent,//
    sip_type_User_Agent,
    sip_type_User_to_User,//
    sip_type_Via,
    sip_type_Warning,
    sip_type_WWW_Authenticate,

    sip_type_P_Access_Network_Info,
    sip_type_P_Answer_State,
    sip_type_P_Asserted_Identity,
    sip_type_P_Asserted_Service,//
    sip_type_P_Associated_URI,
    sip_type_P_Called_Party_ID,
    sip_type_P_Charging_Function_Addresses,
    sip_type_P_Charging_Vector,
    sip_type_P_DCS_Billing_Info,
    sip_type_P_DCS_LAES,
    sip_type_P_DCS_OSPS,
    sip_type_P_DCS_Redirect,
    sip_type_P_DCS_Trace_Party_ID,
    sip_type_P_Early_Media,
    sip_type_P_Media_Authorization,
    sip_type_P_Preferred_Identity,
    sip_type_P_Preferred_Service,//
    sip_type_P_private_Network_Indication,//
    sip_type_P_Profile_Key,
    sip_type_P_Refused_URI_List,//
    sip_type_P_User_Database,
    sip_type_P_Visited_Network_ID
}sip_header_type_t;
#endif //SWEETPOTATO_SIP_HEADER_H
